server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: DEBUG

spring:
  datasource:
    url: jdbc:mysql://online-store-db.mysql.database.azure.com:3306/online_store_db?useSSL=true
    username: a01133518
    password: ENC(OZGe8k8+WP0iotU0yVkDuW6sxEE/I57ukAhbR0gCtDk=)
    initialization-mode: always
  jpa:
    show-sql: true
