server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: DEBUG

spring:
  datasource:
    url: jdbc:sqlserver://online-store-db.database.windows.net:1433;database=online-store-db;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: a01133518
    password: '%Ab0113351801133518%'
    initialization-mode: always
  jpa:
    show-sql: true


